CREATE TABLE [dbo].[Association]
(
	[Association_Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Jeu_Id] UNIQUEIDENTIFIER NOT NULL,
	[Tag_Id] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_JeuAssociation FOREIGN KEY ([Jeu_Id]) REFERENCES [Jeu] ([Jeu_Id]) ON DELETE CASCADE,
	CONSTRAINT FK_TagAssociation FOREIGN KEY ([Tag_Id]) REFERENCES [Tag] ([Tag_Id]) ON DELETE CASCADE,

)
