CREATE TABLE [dbo].[Utilisateur]
(
	[Utilisateur_Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Email] NVARCHAR (320) NOT NULL CONSTRAINT UK_Email UNIQUE,
    [Password] NVARCHAR (64) NOT NULL CONSTRAINT UK_Password UNIQUE,
	[Pseudo] NVARCHAR (64) NOT NULL CONSTRAINT UK_Pseudo UNIQUE,
	[Date_Creation] DATETIME NOT NULL  DEFAULT GETDATE(),
	[Date_Desactivation] DATETIME,

)
